[package]
name    = "sven-input"
version.workspace = true
edition = "2021"

[dependencies]
anyhow        = { workspace = true }
pulldown-cmark = { workspace = true }
tracing       = { workspace = true }
thiserror     = { workspace = true }
serde         = { workspace = true }
serde_json    = { workspace = true }
serde_yaml    = { workspace = true }
sven-model    = { path = "../model" }
sven-session-model = { path = "../session-model" }
atif          = { path = "../atif" }
dirs          = { workspace = true }
chrono        = { workspace = true }
uuid          = { workspace = true }
libc          = { workspace = true }

[dev-dependencies]
tempfile      = { workspace = true }
