[package]
name    = "sven-ci"
version.workspace = true
edition = "2021"

[dependencies]
sven-config    = { path = "../config" }
sven-model     = { path = "../model" }
sven-model-drivers = { path = "../model-drivers" }
sven-tools     = { path = "../tools" }
sven-tools-fs  = { path = "../tools-fs" }
sven-machines      = { path = "../machines" }
sven-session-store     = { path = "../session-store" }
sven-bootstrap = { path = "../bootstrap" }
sven-workspace   = { path = "../workspace" }
sven-hsm       = { path = "../hsm" }
sven-kernel    = { path = "../kernel" }
atif           = { path = "../atif" }
anyhow         = { workspace = true }
serde          = { workspace = true }
serde_json     = { workspace = true }
chrono         = { workspace = true }
tokio          = { workspace = true }
futures        = { workspace = true }
tracing        = { workspace = true }

[dev-dependencies]
sven-session-store   = { path = "../session-store" }
sven-tools   = { path = "../tools" }
async-trait  = { workspace = true }
tempfile     = { workspace = true }
