[package]
name    = "sven-tools"
version.workspace = true
edition = "2021"

[dependencies]
sven-tool-api      = { path = "../tool-api" }
sven-tool-registry = { path = "../tool-registry" }
sven-hsm     = { path = "../hsm" }
sven-image   = { path = "../image" }
anyhow      = { workspace = true }
serde_json  = { workspace = true }
tokio       = { workspace = true }
async-trait = { workspace = true }
tracing     = { workspace = true }
regex       = { workspace = true }
reqwest     = { workspace = true }
html2text   = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
