[package]
name    = "sven-turn"
version.workspace = true
edition = "2021"

[dependencies]
sven-config = { path = "../config" }
sven-model  = { path = "../model" }
sven-tools  = { path = "../tools" }
sven-runtime = { path = "../runtime" }
sven-vocab  = { path = "../vocab" }
sven-session-model = { path = "../session-model" }
anyhow      = { workspace = true }
async-trait = { workspace = true }
futures     = { workspace = true }
regex       = { workspace = true }
serde_json  = { workspace = true }
tokio       = { workspace = true }
tracing     = { workspace = true }
uuid        = { workspace = true }
