[package]
name    = "sven-machines"
version.workspace = true
edition = "2021"

[dependencies]
sven-hsm     = { path = "../hsm" }
sven-vocab   = { path = "../vocab" }
serde       = { workspace = true }
serde_json  = { workspace = true }
uuid        = { workspace = true }
chrono      = { workspace = true }

[dev-dependencies]
tempfile    = { workspace = true }
