// Copyright (c) 2024-2026 Martin Schröder <info@swedishembedded.com>
//
// SPDX-License-Identifier: Apache-2.0
//! `MetricsSchema`: per-step LLM operational and RL-oriented metrics.

use serde::{Deserialize, Serialize};
use serde_json::Value;

/// Per-step LLM operational metrics. Every field is optional.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct StepMetrics {
    /// Total input tokens for this turn, including cached and non-cached.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompt_tokens: Option<u64>,
    /// Tokens generated by the LLM response (including reasoning/tool calls).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub completion_tokens: Option<u64>,
    /// Subset of `prompt_tokens` that were cache hits.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cached_tokens: Option<u64>,
    /// Monetary cost of this step's API call, in USD.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cost_usd: Option<f64>,
    /// Token IDs for the prompt sent to the LLM (RL / retokenization-drift avoidance).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompt_token_ids: Option<Vec<i64>>,
    /// Token IDs for the completion generated by the LLM.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub completion_token_ids: Option<Vec<i64>>,
    /// Log probabilities for each completion token.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub logprobs: Option<Vec<f64>>,
    /// Provider-specific or experimental metrics not covered by the core schema.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extra: Option<Value>,
}
