[package]
name    = "sven-model"
version.workspace = true
edition = "2021"

[dependencies]
sven-model-catalog = { path = "../model-catalog" }
anyhow      = { workspace = true }
serde       = { workspace = true }
serde_json  = { workspace = true }
async-trait = { workspace = true }
futures     = { workspace = true }
